services:
  devenv:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
        USERNAME: ${USERNAME:-dev}
        USER_SHELL: ${USER_SHELL:-bash}
        INSTALL_NEOVIM: ${INSTALL_NEOVIM:-true}
        INSTALL_STARSHIP: ${INSTALL_STARSHIP:-true}
        INSTALL_ATUIN: ${INSTALL_ATUIN:-true}
        INSTALL_MISE: ${INSTALL_MISE:-true}
        INSTALL_EZA: ${INSTALL_EZA:-true}
        INSTALL_ZOXIDE: ${INSTALL_ZOXIDE:-true}
        NODE_VERSION: ${NODE_VERSION:-22.11.0}
    volumes:
      - ${GIT_CREDS_HOST:-/dev/null}:/home/${USERNAME:-dev}/.git-credentials:ro
      - ${PROJECT_PATH}:/home/${USERNAME:-dev}/projects/app
    environment:
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL}
