services:

  # Resets persistent volumes (cache and local state) to build-time defaults.
  # Run after initial build, or anytime you want to discard accumulated
  # data and start fresh.
  reset-volumes:
    image: paul-containers:latest
    pull_policy: never
    user: root
    command: >
      sh -c "cp -a /home/${USERNAME:-dev}/.container-cache/. /mnt/cache/ &&
             cp -a /home/${USERNAME:-dev}/.container-local/. /mnt/local/ &&
             chown -R ${HOST_UID:-1000}:${HOST_GID:-1000} /mnt/cache /mnt/local"
    volumes:
      - container-cache:/mnt/cache
      - container-local:/mnt/local
    # Allows to avoid running it by default
    profiles: ["init"]

  devenv:
    image: paul-containers:latest
    pull_policy: never
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
        USERNAME: ${USERNAME:-dev}
        USER_SHELL: ${USER_SHELL:-bash}
        SUPPLEMENTARY_PACKAGES: ${SUPPLEMENTARY_PACKAGES}
        INSTALL_NEOVIM: ${INSTALL_NEOVIM:-true}
        INSTALL_STARSHIP: ${INSTALL_STARSHIP:-true}
        INSTALL_ATUIN: ${INSTALL_ATUIN:-true}
        INSTALL_MISE: ${INSTALL_MISE:-true}
        NODE_VERSION: ${NODE_VERSION:-22.11.0}
        GIT_AUTHOR_NAME: ${GIT_AUTHOR_NAME}
        GIT_AUTHOR_EMAIL: ${GIT_AUTHOR_EMAIL}
    volumes:
      - ${GIT_CREDS_HOST:-/dev/null}:/home/${USERNAME:-dev}/.git-credentials:ro
      - ${PROJECT_PATH}:/home/${USERNAME:-dev}/projects/app
      - container-cache:/home/${USERNAME:-dev}/.container-cache
      - container-local:/home/${USERNAME:-dev}/.container-local
volumes:
  container-cache:
  container-local:
